h1 = 1000; % first layer
h2 = 100; % second layer
nu = 0.001; % learning rate
mu = 0.7; % momentum
batch = 1; % batch size

tn = 4; % trial number

[w_l_1, w_r_1, b_l_1, b_r_1, w_l_2, w_r_2, w_lr_2, b_l_2, b_r_2, b_lr_2, w_3, b_3, tr_err] = mlp_epoch(X_L, X_R, T, ...
                                                                                                h1, h2, nu, mu, batch);

% do a forward pass for validation set
[a_l_1, a_r_1, ...
 z_l_1, z_r_1, ...
 a_l_2, a_r_2, a_lr_2, ...
 z_2, a_3] = mlp_forward(X_L_val, X_R_val, ...
                         w_l_1, b_l_1, w_r_1, b_r_1, ...
                         w_l_2, b_l_2, w_r_2, b_r_2, w_lr_2, b_lr_2, ...
                         w_3, b_3);

  
val_err = logerr(T_val, a_3);
plotter(tr_err, val_err, tn); % plot errors